level = [
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                       B                   ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                 WWWWWWWWWWWWWWWWWWWW      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W        P         W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 W                  W      ",
        "                 WWWWWWWWWWWWWWWWWWWW      ",
        "                                           ",
        "                                           ",
        "                                           ",
        "                                           ",
    ]